export const REGISTER_MAKE_COMMITMENT_START = "REGISTER_MAKE_COMMITMENT_START"
export const REGISTER_MAKE_COMMITMENT_FAILURE = "REGISTER_MAKE_COMMITMENT_FAILURE"
export const REGISTER_MAKE_COMMITMENT_SUCCESS = "REGISTER_MAKE_COMMITMENT_SUCCESS"

export const REGISTER_COMMIT_NAME_START = "REGISTER_COMMIT_NAME_START"
export const REGISTER_COMMIT_NAME_FAILURE = "REGISTER_COMMIT_NAME_FAILURE"
export const REGISTER_COMMIT_NAME_SUCCESS = "REGISTER_COMMIT_NAME_SUCCESS"
export const REGISTER_COMMIT_NAME_RESET = "REGISTER_COMMIT_NAME_RESET"

export const REGISTER_NAME_START = "REGISTER_NAME_START"
export const REGISTER_NAME_FAILURE = "REGISTER_NAME_FAILURE"
export const REGISTER_NAME_SUCCESS = "REGISTER_NAME_SUCCESS"